apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: service-alerts
  namespace: monitoring
spec:
  groups:
  - name: service.rules
    rules:
    - alert: ServiceDown
      expr: up == 0
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "Service {{ $labels.service }} is down"
        description: "Service {{ $labels.service }} has been down for more than 5 minutes"
    
    - alert: HighLatency
      expr: http_request_duration_seconds{quantile="0.9"} > 2
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High latency for {{ $labels.service }}"
        description: "90th percentile latency is above 2 seconds for {{ $labels.service }}"
    
    - alert: HighErrorRate
      expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.1
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High error rate for {{ $labels.service }}"
        description: "Error rate is above 10% for {{ $labels.service }}"