apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: ecommerce
type: Opaque
data:
  username: YWRtaW4=  # admin
  password: ${BASE64_ENCODED_PASSWORD}  # Replace with actual base64 encoded password