global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'cart-service'
    static_configs:
      - targets: ['cart-service:3000']

  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:3001']

  - job_name: 'request-service'
    static_configs:
      - targets: ['request-service:3002']