apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: request-service-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: request-service
  endpoints:
  - port: metrics
    interval: 15s
  namespaceSelector:
    matchNames:
    - ecommerce